apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: als
  annotations:
    build: "20250610_104224"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        build: "20250610_104224"
    spec:
      containers:
        - name: nginx
          image: nginx:1.28.0-alpine
          command:
            - sh
            - -c
            - |
              set -e
              apk add --no-cache git
              git clone https://github.com/wsva/als_nginx /als_nginx
              nginx -c /als_nginx/default.conf -g 'daemon off;'
          ports:
            - containerPort: 443
          volumeMounts:
            - name: ssl
              mountPath: /ssl
      volumes:
        - name: ssl
          hostPath:
            path: /als/ssl
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: als
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      nodePort: 443